global_costmap:
  global_frame: map
  robot_base_frame: robot_footprint
  update_frequency: 10.0
  publish_frequency: 10.0
  static_map: true
  resolution: 0.05
  cost_scaling_factor: 10.0
  inflation_radius: 0.02